augment: true
batch_size: 256
data_fraction: 1.0
dataset: cifar10
epochs: 50
label_noise: 0.3
lr: 0.0001
model: resnet18
optimizer: lion
save_dir: ./results_hypothesis
scheduler: cosine
seed: 123
weight_decay: 0.01
workers: 4
